config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
    # Defines the root path route ("/")
  root 'users#index'
    get '/users'                   => 'users#index'
    get '/users/:id'               => 'users#show',as: 'user'
    get '/users/:user_id/posts', to: 'posts#index', as: 'user_posts'
    get '/users/:user_id/posts/new' => 'posts#new'
    get '/users/:user_id/posts/:post_id' => 'posts#show',  as: 'post'
    post '/users/:id/posts/create', to: 'posts#create'
    get '/users/:id/posts/:post_id/comments/new', to: 'comments#new'
    post '/users/:id/posts/:post_id/comments/create', to: 'comments#create'
    post '/users/:id/posts/:id/likes/create', to: 'likes#create'
  # Defines the root path route ("/")

  resources :users do
    resources :posts do
      resources :comments
      post 'likes', to: 'likes#create' # Nested route for creating a like
    end
  end
  
  #Routes for API endpoints
  namespace :api, defaults: { format: :json } do
    resources :users, only: [] do
      resources :posts, only: [:index] do
        resources :comments, only: [:index, :create]
      end
    end
  end
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    can :read, Post, public: true
    can :read, Comment, public: true

    # user can read their own posts
    return unless user.present?

    can :read, Post, user_id: user.id
    can :destroy, Post, author_id: user.id

    can :read, Comment, user_id: user.id
    can :destroy, Comment, author_id: user.id

    return unless user.role == 'admin' # permission for admins

    can :destroy, Post
    can :destroy, Comment
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :author, class_name: 'User'
  belongs_to :post, counter_cache: :comments_counter

  after_save :update_comments_counter

  def update_comments_counter
    post.update(comments_counter: post.comments.count)
  end
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :author, class_name: 'User'
  belongs_to :post

  after_save :update_likes_counter

  # private

  def update_likes_counter
    post.increment!(:likes_counter)
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :author, class_name: 'User', foreign_key: 'author_id'
  has_many :comments, foreign_key: 'post_id', dependent: :destroy
  has_many :likes, foreign_key: 'post_id', dependent: :destroy

  after_save :update_posts_counter

  def self.five_recent_comments(post)
    post.comments.order(created_at: :desc).limit(5)
  end

  validates :title, presence: true, length: { maximum: 250 }
  validates :comments_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :likes_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  # private

  def update_posts_counter
    author.update(posts_counter: author.posts.count)
  end
end

app/models/user.rb
class User < ApplicationRecord
  before_validation :set_default
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
  has_many :posts, foreign_key: 'author_id'
  has_many :comments, foreign_key: 'author_id'
  has_many :likes, foreign_key: 'author_id'

  validates :name, presence: true
  validates :posts_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  def three_most_recent_posts
    posts.order(created_at: :asc).limit(3).reverse
  end

  def set_default
    self.name = email.split('@')[0]
    self.posts_counter = 0
  end
end

app/controllers/api/application_controller.rb
class Api::ApplicationController < ApplicationController
  respond_to :json
end

app/controllers/api/comments_controller.rb
class Api::CommentsController < Api::ApplicationController
  def index
    post = Post.find(params[:post_id])
    comments = post.comments
    render json: comments
  end

  def create
    post = Post.find(params[:post_id])
    comment = post.comments.build(comment_params)
    comment.user = current_user

    if comment.save
      render json: comment, status: :created
    else
      render json: { error: 'Comment cannot be added.' }, status: :unprocessable_entity
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:content)
  end
end

app/controllers/api/posts_controller.rb
class Api::PostsController < ApplicationController
  def index
    user = User.find(params[:user_id])
    posts = user.posts
    render json: posts
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # def current_user
  #   User.first
  # end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!, only: [:create]
  def new
    @comment = Comment.new
  end

  def create
    @comment = Comment.new(comment_params)
    @comment.author_id = current_user.id
    @comment.post_id = params[:post_id]

    if @comment.save
      redirect_to users_path
    else
      render :new
    end
  end

  def destroy
    @comment = Comment.find_by(post_id: params[:post_id], id: params[:id])
    if @comment
      @comment.destroy
      redirect_to user_post_path(@comment), notice: 'Comment deletion successfull.'
    else
      redirect_to user_post_path(@user, @post), alert: 'Comment not found'
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:text)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    @like = Like.new
    @like.author_id = current_user.id
    @like.post_id = params[:post_id]

    if @like.save
      redirect_to(request.referrer || root_path)
    else
      render :new
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, only: [:create]
  def index
    @posts = Post.where(author_id: params[:user_id])
    @user = User.find(params[:user_id])
  end

  def show
    @post = Post.find(params[:post_id])
    @user = @post.author
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.author_id = current_user.id
    @post.likes_counter = 0
    @post.comments_counter = 0

    if @post.save
      redirect_to users_path
    else
      render :new
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to root_path
  end

  private

  def post_params
    params.require(:post).permit(:title, :text)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end
end

app/helpers/api/application_helper.rb
module Api::ApplicationHelper
end

app/helpers/api/comments_helper.rb
module Api::CommentsHelper
end

app/helpers/api/posts_helper.rb
module Api::PostsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/new.html.erb
<h2>Add you comments</h2>

<%= render 'shared/comment', post_id: params[:post_id] %>

app/views/posts/index.html.erb
<%= render 'shared/user_info', user: @user %>

<div class='indexbox'>
  <% @posts.includes(:author).each do |post| %>
    <div class='box commentsbox'>
      <a href='/users/<%= post.author_id%>/posts/<%= post.id%>'><%= post.title%></a>
      <p>
        <%= post.text%>
      </p>
      <p class='counters'>Comments: <%= post.comments_counter %> Likes: <%= post.likes_counter %></p>
  </div>
  <div class='box'>
    <% Post.includes(:author, :post).five_recent_comments(post).each do |comment| %>
      <p><%= comment.author.name %> - <%= comment.text %></p>
    <% end %>
  </div>
  <br />
  <% end %>
  <div class='btn'>
    <button class='my-btns'>Pagination</button>
  </div>
</div>

app/views/posts/new.html.erb
<h2>Create your New Post</h2>

<%= form_with url: "/users/21/posts/create", model: @post do |form| %>
    <div>
        <%= form.label :title %>
        <%= form.text_field :title %>
    </div>
    <div>
        <%= form.label :text %>
        <%= form.text_field :text %>
    </div>
    <%= form.submit %>
<% end %>

app/views/posts/show.html.erb
<div class='dis_contt'>
    <div class='box'>
        <div class='posts_container'>
            <p><%= @post.title%> by <%= @post.author.name%></p>
            <p>Comments: <%= @post.comments_counter %> Likes: <%= @post.likes_counter %></p>
            <% if can? :destroy, @post %>
        <%= form_with(model: @post, url: user_post_path(@user, @post), method: :delete, data: { confirm: "Please confirm?" }) do |form| %>
            <%= form.hidden_field :delete, value: "#{@post.id}"%>
            <%= form.submit "Delete Post" %>
            <% end %>
        <% else %>
        <% end %>
        </div>
        <p>
            <%= @post.text%>
        </p>
    </div>
    <br />
    <%= render 'shared/like' %>
    <a href="/users/<%= @post.author.id %>/posts/<%= @post.id %>/comments/new">Comment</a>
    <div class='box'>
        <% @post.comments.each do |comment|%>
            <p><%= comment.author.name%>: <%= comment.text %></p>    
            <% if can? :destroy, comment %>
        <%= form_with(model: @comment, url: user_post_comment_path(@user, @post, comment), method: :delete, data: { confirm: "Please confirm?" }) do |form| %>
            <%= form.hidden_field :delete, value: "#{comment.id}"%>
            <%= form.submit "Delete" %>
            <% end %>
        <% else %>
        <% end %>
        <% end %>
    </div>
</div>

app/views/users/index.html.erb
<div>
    <a href='/users/new/posts/new'> Add New Post</a>
</div>
<% @users.each do |user| %>
    <%= render partial: 'shared/user_info', locals: { user: user } %>
<% end %>

app/views/users/show.html.erb
<%= render 'shared/user_info', user: @user %>

<div class='info'>
    <div class='box'>
        <h1>Bio</h1>
        <p>
            <%= @user.bio %>
        </p>
    </div>
    <% @user.three_most_recent_posts.each do |post| %>
        <div class='box'>
          <h2>Post <%= post.title %></h2>
            </h2>
            <p>
                <%= post.text %>
            </p>
            <p class='counters'>Comments: <%= post.comments_counter %> Likes: <%= post.likes_counter %></p>
        </div>
    <% end %>

    <a href='/users/<%= @user.id%>/posts' class='my-btns'>See all posts</a>
</div>